apistore.protocol=http
apistore.host=dualstack.internal-prodalb-867207337.ap-south-1.elb.amazonaws.com
apistore.port=
apistore.basePath=

apistore.api.getProductId.path=/wishlist-service/customers/{customerId}
apistore.api.getProductId.connectTimeout=500
apistore.api.getProductId.readTimeout=25000
