#server port
server.port=8082
server.servlet.context-path = /suggestionandsearch-service

#aws elasticsearch configuration
aws.es.endpoint=https://vpc-productionouat-vyv5ugfwvsz7sonvlo4g6lfgvi.ap-south-1.es.amazonaws.com
aws.es.accessKey=AKIARDAWOJLSV2T3HG2M
aws.es.secretKey=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
aws.es.region=ap-south-1

#search and suggestion index name
auto.search.index.name=autosearchindex
auto.suggestion.index.name=autosuggestionindex

#Demand Store Auth Service URL
auth.service.demand.store.url=http://dualstack.internal-prodalb-867207337.ap-south-1.elb.amazonaws.com/demandstore-auth-service

