#service port
server.port = 7072
server.servlet.context-path=/customer-order-service


#
productImageAndProductUrl.api.url=http://stageapi.taggd.com/plp-pdp-service/internal/product-name-product-img
#
customerServiceUrl =http://stageapi.taggd.com/customer-service/


#Redis
#spring.redis.host=ouat-v2-stage-redis.bcjfhh.0001.aps1.cache.amazonaws.com
spring.redis.host=localhost
#DB
spring.datasource.url = jdbc:mysql://ouatv2user@ouat-v2-dev.ctpchpfqiwf1.ap-south-1.rds.amazonaws.com:3306/orders
spring.datasource.username = ouatv2user 
spring.datasource.password = XcXpXC!Xrkv4WSr
spring.datasource.platform = mysql
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.show_sql = true
spring.jpa.properties.hibernate.use_sql_comments = true
spring.jpa.properties.hibernate.format_sql = true

spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.test-on-borrow=true

#Demand Store Auth Service URL
auth.service.demand.store.url=http://stageapi.taggd.com/demandstore-auth-service


order.confirmation.banner=https://taggd.gumlet.io/prod-banner/order-place-img.gif
internal.secure.accessKey=8NvwaKlnz3hvFOxBO69z58dFcPDPlAmU

cuttly.get.api.url = https://cutt.ly/team/API/index.php?action=shorten
cuttly.access.key = 1e0bc5f16783eb39bcd8cba0270ca3144090c
is.referral = true
