#server port
server.port=8082
server.servlet.context-path = /suggestionandsearch-service

#aws elasticsearch configuration
aws.es.endpoint=https://search-stageouat-5vfh2clcwwy34xg2is4f64i3gm.ap-south-1.es.amazonaws.com
aws.es.accessKey=AKIARDAWOJLSTI7WZE54
aws.es.secretKey=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
aws.es.region=ap-south-1

#search and suggestion index name
auto.search.index.name=autosearchindex
auto.suggestion.index.name=autosuggestionindex

#Demand Store Auth Service URL
auth.service.demand.store.url=http://stageapi.taggd.com/demandstore-auth-service