#service port
server.port = 9095
server.servlet.context-path = /checkout-service


#DB
spring.datasource.url = jdbc:mysql://ouat-v2-dev.ctpchpfqiwf1.ap-south-1.rds.amazonaws.com:3306/orders
spring.datasource.username = ouatv2user
spring.datasource.password = XcXpXC!Xrkv4WSr
spring.datasource.platform=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.test-on-borrow=true

#Redis
spring.redis.host=ouat-v2-stage-redis.dxdrtd.ng.0001.aps1.cache.amazonaws.com
#to run on local
#spring.redis.host=localhost
spring.redis.database=0
spring.redis.port=6379
#redis doesn't have a password, so it's the default password
spring.redis.password=
# Connection timeout unit: ms (MS)
spring.redis.timeout=40
# The maximum idle connection in the connection pool. The default value is 8
spring.redis.jedis.pool.max-idle=10
#The minimum idle connection in the connection pool. The default value is also 0
spring.redis.jedis.pool.min-idle=3
# The maximum number of jedis instances in the connection pool. If the value is - 1, it means unlimited; if the pool has been fully allocated, the status will become exhausted.
spring.redis.jedis.pool.max-active=200
# The maximum waiting time of available connections, in milliseconds. The default value is - 1, which means never timeout. If the timeout occurs, the JedisConnectionException is thrown directly
spring.redis.jedis.pool.max-wait=10000

spring.banner.image.location=classpath:banner.txt

max.cart.value.cod=10000

#API End Points
auth.service.demand.store.url=http://stageapi.taggd.com/demandstore-auth-service
customer.service.customer.history.url =http://stageapi.taggd.com/customer-service/credit/history
inventory.service.inventory.update.url =http://stageapi.taggd.com/inventory-service/internal/update-inventory
customer.service.add.customer.url =http://stageapi.taggd.com/customer-service/internal/add-guest-user
inventory.service.inventory.add.url =http://stageapi.taggd.com/inventory-service/internal/v1/add-inventory


#auth.service.email.sms.service.url =http://stageapi.taggd.com/email-sms-service/
promotion.service.promotion.service.url =http://stageapi.taggd.com/promotion-service/internal/add-in-log

notification.service..order.alert.url=http://stageapi.taggd.com/notification-sender/send-place-alert

thread-pool.corePoolSize=32
thread-pool.maxPoolSize=64
thread-pool.queueCapacity=1000
thread-pool.threadNamePrefix="thread-pool-"


cart.service.url=http://stageapi.taggd.com/cart-service/internal/shopping-cart
#cart.service.url=http://localhost:7074/cart-service/internal/289/show-shopping-cart/WEB
property.environment = stage

internal.secure.accessKey=8NvwaKlnz3hvFOxBO69z58dFcPDPlAmU


#email.sms.service.URL
email.sms.service.baseurl=https://1agf4jvxa2.execute-api.ap-south-1.amazonaws.com/email-sms-service

#env
env=stage


order.confirmation.banner=https://taggd.gumlet.io/prod-banner/order-place-img.gif
https://api.razorpay.com/v1/customers


#Demond Angular URL For Call Back
callbackurl=http://stage.taggd.com/callback?

