payment.razorPay.url=https://api.razorpay.com/v1/orders
payment.razorPay.secretKey=qLXPubfrRNnEqgRN7jLFD4iG
payment.razorPay.accessKey=rzp_test_kymQ6rJPZnFIzj
payment.razorPay.customer=https://api.razorpay.com/v1/customers
