apistore.protocol=http
apistore.host=dualstack.internal-prodalb-867207337.ap-south-1.elb.amazonaws.com
apistore.port=
apistore.basePath=

apistore.api.customerCredit.path=/customer-service/internal/credit/{customerId}
apistore.api.customerCredit.connectTimeout=500
apistore.api.customerCredit.readTimeout=25000

apistore.api.customerAddress.path=/customer-service/internal/{customerId}/address
apistore.api.customerAddress.connectTimeout=500
apistore.api.customerAddress.readTimeout=20000

apistore.api.customerShoppingCartDetails.path=/cart-service/internal/{customerId}/show-shopping-cart/{platform}
apistore.api.customerShoppingCartDetails.connectTimeout=500
apistore.api.customerShoppingCartDetails.readTimeout=20000

apistore.api.customerPromoCodeDetails.path=/promotion-service/internal/apply-promo
apistore.api.customerPromoCodeDetails.connectTimeout=500
apistore.api.customerPromoCodeDetails.readTimeout=20000

apistore.api.skusInventoryCodDetails.path=/plp-pdp-service/checkout/skus/details
apistore.api.skusInventoryCodDetails.connectTimeout=500
apistore.api.skusInventoryCodDetails.readTimeout=20000