payment.razorPay.url=https://api.razorpay.com/v1/orders
payment.razorPay.secretKey=ubrGm8QGDYPeZRgQuqEfnMHU
payment.razorPay.accessKey=rzp_live_uYJShTfS2m9kkP
payment.razorPay.customer=https://api.razorpay.com/v1/customers
