#service port
server.port = 7078
server.servlet.context-path = /demandstore-auth-service

jwt.secret=SUtD+N:Ksv28V@]dg7HIHL)V(O)APt


#Redis
spring.redis.host=ouat-v2-stage-redis.bcjfhh.0001.aps1.cache.amazonaws.com
#spring.redis.host=localhost
spring.redis.database=0
spring.redis.port=6379
#redis doesn't have a password, so it's the default password
spring.redis.password=
# Connection timeout unit: ms (MS)
spring.redis.timeout=10
# The maximum idle connection in the connection pool. The default value is 8
spring.redis.jedis.pool.max-idle=10
#The minimum idle connection in the connection pool. The default value is also 0
spring.redis.jedis.pool.min-idle=3
# The maximum number of jedis instances in the connection pool. If the value is - 1, it means unlimited; if the pool has been fully allocated, the status will become exhausted.
spring.redis.jedis.pool.max-active=200
# The maximum waiting time of available connections, in milliseconds. The default value is - 1, which means never timeout. If the timeout occurs, the JedisConnectionException is thrown directly
spring.redis.jedis.pool.max-wait=10000

#Homepage Setup Service
#homepage.setup.service.baseurl=http://localhost:8084/
homepage.setup.service.baseurl=http://172.31.37.63:8084/
