package com.ouat.orderService.constants;

public class SqlConstant {
	public static final String ORDER_ITEM_SHIPMENT_DETAILS_QUERY = "SELECT ooi.id AS order_id,o.id,ooi.order_item_total_amount AS price,ooi.sku,ooi.qty AS quantity,(SUM(ooi.order_item_credit_applied) + SUM(ooi.order_item_payable)) AS invoice_value, ooi.order_item_payable AS cod_amount, (SUM(ooi.order_item_platform_offered_discount) + SUM(ooi.order_item_promo_discount)) AS total_discount, p.name AS item_name, ooi.shipping_charges AS shipping_charge, o.payment_method, ooi.estimated_shipped_date as shipped_by_date ,o.order_date as order_date,o.updated_date AS order_updated_date, DATEDIFF(ooi.estimated_shipped_date, o.order_date) AS esd, p.name AS item_name, vd.company As from_name, vd.gst_number AS pickup_gstin, va.address_line_1 AS from_address, va.pincode AS from_pincode, vc.contact_number AS from_phone_number,cca.house_owner_name AS to_name, cca.address AS to_address, cca.pincode AS to_pincode, IF((cca.mobile_number=NULL OR cca.mobile_number='') , cc.mobile,cca.mobile_number) AS to_phone_number,cc.email AS to_email FROM orders.order_item ooi JOIN orders.order o ON (ooi.order_id = o.id) JOIN orders.order_shipment_detail osd ON ( ooi.order_id = osd.order_id ) INNER JOIN customers.customer_addresses cca ON ( osd.address_id = cca.id ) JOIN customers.customer cc ON(cca.customer_id=cc.id) JOIN products.product_item pi ON (pi.sku = ooi.sku) JOIN products.product p ON (pi.product_id = p.id) JOIN supplychain.vendor_details vd ON (vd.id = p.vendor_id) JOIN supplychain.vendor_address va ON (va.vendor_id = vd.id) JOIN supplychain.vendor_contact vc ON (vc.vendor_id = va.vendor_id) WHERE ooi.id IN (%s) AND ooi.order_status_id IN (11,12,3) AND o.order_type='DemandStore' AND va.address_type= 'SHIPPING_ADDRESS'";

	public static final String UPSERT_STATUS_OF_ORDER_SHIPMENT_DETAILS = "INSERT INTO orders.awb_meta_data (order_item_id, awb, courrier_partner, transporter_courier, routing_code, created_by, created_at) VALUES (?,?,?,'pickrr',?,'BEST_SHIIPER_API', Convert_tz(Now(), '+00:00', '+05:30')) ON DUPLICATE KEY UPDATE awb=?, courrier_partner=?, routing_code=?, updated_by='BEST_SHIIPER_API', updated_at= Convert_tz(Now(), '+00:00', '+05:30')";
	
	public static final String UPSERT_STATUS_OF_ORDER_SHIPMENT_QUERY = "INSERT INTO orders.order_tracking_detail (order_item_id, awb, courrier_partner, transporter_courier, created_at, created_by) VALUES (?,?,?,'pickrr', Convert_tz(Now(), '+00:00', '+05:30'), 'BEST_SHIIPER_API') ON DUPLICATE KEY UPDATE awb=?, courrier_partner=?, updated_at= Convert_tz(Now(), '+00:00', '+05:30'), updated_by='BEST_SHIIPER_API'";
	
	public static final String UPDATE_STATUS_OF_ORDER_ITEMS_QUERY = "UPDATE orders.order_item SET order_status_id = 12, updated_by = 'AllocateBestShipperService', updated_at = Convert_tz(Now(), '+00:00', '+05:30') WHERE id = ?";

}
